// Load/assign collections here

/**
 * @param _id {String} Unique identifier generated by mongo.
 * @param date {String} The date that this entry belongs to. Format: YYYY-MM-DD.
 * @param weight {Number} The current weight (in pounds) on this day.
 * @param result {String} One of good|bad|ok.
 */
Entries = new Meteor.Collection("entries");

/**
 * @param _id {String} Unique identifier generated by mongo.
 * @param date {String} The date that this entry belongs to. Format: YYYY-MM-DD.
 * @param order {Number} The order that this should appear in the entry.
 * @param name {String} The name of this exercise.
 * @param sets {Array} The array of sets in this exercise.
 *     @param weight {Number} The current weight (in pounds) lifted in this set.
 *     @param reps {Number} The number of repetitions in this set.
 */
Exercises = new Meteor.Collection("exercises");

/**
 * @param _id {String} Unique identifier generated by mongo.
 * @param date {String} The date that this entry belongs to. Format: YYYY-MM-DD.
 * @param order {Number} The order that this should appear in the entry.
 * @param type {String} The type of mean that this is: eg. Breakfast.
 * @param details {String} Small explanation of what was eaten.
 */
Meals = new Meteor.Collection("meals");